### ISSUE TITLE
Mod Updating Support

### ISSUE THREAD

**Issue by doublee313** [alimalkhalifa/conanmanager#2]
Sorry I don't know where to post this but I'd like to get in contact with Almalkhalifa to discuss adding mod updates. I have a utility that does it now and some other features that would be nice to see in this. You can reach me at **********@gmail.com or easy on Discord: https://discord.gg/******

Thanks. I would also like to beta test if possible. You can delete this after you read it since its not an issue. Thanks.

**Comment by alimalkhalifa** [comment]
Implemented in commit 7bd638687224b5b2ed59ed42081e53f0c74e6edd
Thanks for the suggestion!
